### ISSUE TITLE
[SDK文档] SDK文档出现了亿些错误，望修正

### ISSUE THREAD

**Issue by lincannm** [StageGuard/mirai-rhinojs-sdk#2]
<https://stageguard.top/p/mirai-rhinojs-sdk.html>
# Mirai
### ● `<constructor>` Mirai.GroupSenderInfo(`Number` id, `String` name, `**Mirai.MessageTypeConst.GroupPermission**` permission, JSON group)

该构造函数的说明中，permission参数类型不应该是`Mirai.MessageTypeConst.GroupPermission`，而应该是`Mirai.GroupInfo.Permission`

### ●  `**Mirai.MessageTypeConst.GroupPermission**` getPermission()

犯了同上的错误，返回类型不对
 
### ●  `**Mirai.GroupInfo.GroupPermission**` gePermission()

返回类型仍然不对，应该是`Mirai.GroupInfo.Permission`，方法名还差了个t，应该为**getPermission()**

# **FiloIO**
标题错误，应该为**FileIO**

# NetworkUtils
### ● `**java.io.InputStream**` `static` getInputStream(`String` url[, `Array` headers])
返回类型错误。看了一下源码，1576行左右，返回的数据应该是这样子的：
```JavaScript
return [connection.getContentLength(), connection.getInputStream()];
```
返回的是个数组，而不是正宗的`java.io.InputStream`。建议更新一下MiraiBot_HTTP.js，将该行改为
```JavaScript
return connection.getInputStream();
```
或者修改SDK文档

**Comment by StageGuard** [comment]
感谢反馈，文档写的比较匆忙，这个下个周四就修改并关闭该issue

**Comment by lincannm** [comment]
> 感谢反馈，文档写的比较匆忙，这个下个周四就修改并关闭该issue

好的

**Comment by StageGuard** [comment]
@lincannm 由于下个版本(1-2天之内release)将会有breaking changes，故文档修改工作将与下个版本的发布一起提交。
issue关闭时间推迟1-2天。

**Comment by lincannm** [comment]
还有一个问题

在文档开头的 **类型预览** 点击Mirai类下的所有子类的链接都没有反应，不能直接转到其标题附近，造成了查阅文档的不方便

比如我在里面点击Mirai下的GroupSenderInfo，没有反应，通过查看网页的html源码，发现是链接内id与标题的id属性不一致。

查看文档网页源码84行：

```HTML
<li><a href="#Mirai.GroupSenderInfo">GroupSenderInfo</a> - 群信息发送者</li>
```

链接对应的id是`Mirai.GroupSenderInfo`

查看418行：

```HTML
<h2 id="Mirai-GroupSenderInfo"><a href="#Mirai-GroupSenderInfo" class="headerlink" title="Mirai.GroupSenderInfo"></a>Mirai.GroupSenderInfo</h2><p>Mirai.GroupSenderInfo为hook群组消息时返回的消息发送者的一些信息。</p>
```

id却变成了`Mirai-GroupSenderInfo`

点击Mirai NetworkUtils LinuxShell可以跳转到各自的标题。除了Mirai的子类，FileIO也不行，是因为标题已经写成FiloIO了

**Comment by StageGuard** [comment]
@lincannm 跳转问题应该是Hexo主题的bug，我会想办法一起解决

**Comment by StageGuard** [comment]
已修改
